### ISSUE TITLE
Transform error

### ISSUE THREAD

**Issue by slackfoo** [MISP/MISP-maltego#17]
Running into this error when executing MISP Transform:

Transform to MISP Event returned with an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/canari/maltego/runner.py", line 130, in local_transform_runner
    config
  File "/usr/local/lib/python3.7/site-packages/MISP_maltego/transforms/attributetoevent.py", line 109, in do_transform
    for e in events_json['response']:
KeyError: 'response' (from entity "1dnscontrol.com")
Transform to MISP Event done (from entity "1dnscontrol.com")
Transform in MISP? returned with an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/canari/maltego/runner.py", line 130, in local_transform_runner
    config
  File "/usr/local/lib/python3.7/site-packages/MISP_maltego/transforms/attributetoevent.py", line 36, in do_transform
    for e in events_json['response']:
KeyError: 'response' (from entity "1dnscontrol.com")

**Comment by cvandeplas** [comment]
Which version of misp_maltego are you using? 
Which version of MISP and PyMISP do you have?

**Comment by cvandeplas** [comment]
I am not able to reproduce this issue, so without more info I really cannot help you.
