### ISSUE TITLE
AttributeError: type object 'meta' has no attribute 'namespace' in safedexml packages

### ISSUE THREAD

**Issue by kluo84** [MISP/misp-maltego#60]
I got the error why trying to run `canari create-profile MISP_maltego`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/canari/pkgutils/maltego.py", line 537, in __del__
    self.close()
  File "/usr/local/lib/python3.7/site-packages/canari/pkgutils/maltego.py", line 812, in close
    self._write_pending()
  File "/usr/local/lib/python3.7/site-packages/canari/pkgutils/maltego.py", line 722, in _write_pending
    self.write_file(transform_set_def['filename'], transform_set_xml)
  File "/usr/local/lib/python3.7/site-packages/canari/pkgutils/maltego.py", line 705, in write_file
    contents = contents.render(encoding='utf-8', fragment=True, pretty=True)
  File "/usr/local/lib/python3.7/site-packages/safedexml/__init__.py", line 419, in render
    data.extend(self._render(nsmap))
  File "/usr/local/lib/python3.7/site-packages/safedexml/__init__.py", line 461, in _render
    if self.meta.namespace:
AttributeError: type object 'meta' has no attribute 'namespace'
```
I see there was a Meta class, but I changed Meta to meta, it still didn't work. Have no clue how to fix this. Please advise.

**Comment by LookingAround456** [comment]
Did you get it fixed? i am running into the same problem.

**Comment by cvandeplas** [comment]
Canari is unfortunately not maintained anymore. This can cause issues when trying to install MISP Maltego.
the good news is that a new MISP & Maltego integration is coming soon. In the meantime the best might be to either try on an older python version, or use the [integration in the transform hub](https://github.com/MISP/MISP-maltego/blob/master/README.md#transform-hub).
